version: '3'
services:
  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: softy-pinko-front-end:task6
    ports:
      - "9000:9000"

  back-end:
    image: softy-pinko-back-end:task6
    deploy:
      replicas: 2
    ports:
      - "5252"

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: softy-pinko-proxy:task6
    ports:
      - "80:80"
    depends_on:
      - front-end
      - back-end
